### ISSUE TITLE
What model is evaluated in the "ours" model in CPU Real time Inference

### ISSUE THREAD

**Issue by LovExtreme** [WongKinYiu/CrossStagePartialNetworks#15]
I read through the repository but can't figure out which model is used in that section. Could you please tell me where I can find it? Thank you.

**Comment by WongKinYiu** [comment]
it is in table 5.
![image](https://user-images.githubusercontent.com/12152972/75129161-b1a2a980-5702-11ea-9af8-da9f268ae11f.png)
