### ISSUE TITLE
Problems understanding the concept of "csdarknet53s-panet-spp"

### ISSUE THREAD

**Issue by mariedde** [WongKinYiu/CrossStagePartialNetworks#19]
@WongKinYiu 

Hello! Thanks for your great work! I want to use "csdarknet53s-panet-spp" and "yolov3-spp" in my master thesis. I understand yolov3-spp however I don't quite understand csdarknet53s-panet-spp.  

1) So first of all what's the difference between "csdarknet53s" and "csdarknet53m"?
2) The detector is called "panet" however the cfg-file also has 3 yolo layers? So what's the difference between panet and yolo? Is it just that the augmented bottom-up pathway was added to the FPN architecture, that the adaptative feature pooling layer was added after this extension and that the backbone in general (CsDarknet) is different because it uses partitial dense blocks?
3) Also the main difference between vanilla Darknet and CsDarknet is not quite clear to me. So is just that we use several partitial dense blocks in which we basically split the base feature map, concat one part with several feature maps and put the concatenation in the transition layer while the other part of the base feature map is then combined with the transitioned concatenation?

Also for training csdarknet53s-panet-spp we need "csdarknet53.conv.104" as you wrote in issue #17. However I can't find the file. Could you please link it?

**Comment by WongKinYiu** [comment]
1. `csdarknet53s` deletes some layers of `csdarknet53`; `csdarknet53m` reduces channel number of some layers of `csdarknet53`. 
2. panet: [path aggregation network](https://arxiv.org/abs/1803.01534), which gets 1st place on coco17 instance segmentation.
3. yes
4. no, all of models trained by pytorch are training from scratch.

**Comment by mariedde** [comment]
Thanks for your answer.
I see panet is the method mentioned in the arxiv paper. However I thought because of the path aggregation panet only makes 1 prediction from the "adaptative feature pooling layer". However the "csdarknet53s-panet-spp.cfg file makes 3 predictions like yolov3. The basic difference however I think is that this panet samples the 2-times upsampled feature maps down again (which yolov3 does not) and makes predictions in an opposite way. Yolov3 makes predictions from feature maps getting higher resolution while panet makes predictions from feature maps getting smaller again.

I hope I did understand the concept now correctly.

**Comment by AlexeyAB** [comment]
@mariedde 

You should distinguish what belongs to what:

* Backbones: AlexNet, VGG16, ResNet50, ResNext50, Darknet53, CSP-Darknet53, Inception v3

* Path-aggregation blocks: FPN, PANet, NAS-FPN, Fully-connected FPN, BiFPN, ASFF

* Additional blocks: SPP, RFB, ...

* Heads: Faster-RCNN, Mask-RCNN, SSD, Yolo

**Original PANet uses**: ResNet50 + PANet + Mask-RCNN

**csdarknet53s-panet-spp uses:** CSP-Darknet53 + PANet + Yolo


![69334349-917ace80-0c6b-11ea-94fb-045e60df001c](https://user-images.githubusercontent.com/4096485/76513125-dcad2d00-6466-11ea-8839-0bae15dad8b1.png)

**Comment by mariedde** [comment]
Ah thanks AlexeyAB. That seperation makes it more clear.

**Comment by pliablepixels** [comment]
This is actually a good question for many of us, @AlexeyAB 

So when we are using:

```
csresnext50-panet-spp-original-optimal.cfg
csresnext50-panet-spp-original-optimal_final.weights
```

with darknet in OpenCV (`cv2.readFromDarknet`), what belongs to what?

- Is the 'backbone' darknet? Or is it cspn ? 
- How do resnext50 and panel feature in?
- the cfg file uses yolo, is that the "head"?

I'm modifying my code to support multiple models - I was originally only supporting yolov3, yolov3tiny, now I've added csresnext50-panet-spp and I want to make sure I am using the right terminology in my config files :-)
