### ISSUE TITLE
YOLOv3-tiny-PRN.cfg feature maps are inconsistent in size and cannot be added?

### ISSUE THREAD

**Issue by cuixing158** [WongKinYiu/CrossStagePartialNetworks#23]
![image](https://user-images.githubusercontent.com/22857777/80691962-80c86180-8b03-11ea-8323-403e963f9c50.png)

**Comment by WongKinYiu** [comment]
![image](https://user-images.githubusercontent.com/12152972/80695840-11557080-8b09-11ea-9790-a642a5b020a0.png)

**Comment by cuixing158** [comment]
The meaning of case A is that when the number of input channels is less than the channels connected to the from layer of the shortcut, the output channel takes the smallest one? I still can not fully understand the meaning of the picture, thank you for detail!

**Comment by WongKinYiu** [comment]
Output shape will always same as input shape (-1 layer).

**Comment by cuixing158** [comment]
那就是說輸出shape與input相同，通道是如何相加的呢？是從from的那個層隨機選c個匹配通道相加嗎？謝謝！

**Comment by WongKinYiu** [comment]
always add channel **0** to **min(channel_input, channel_from)**.

**Comment by cuixing158** [comment]
thanks very much!
