### ISSUE TITLE
Does CSP model need to increase training times

### ISSUE THREAD

**Issue by zsgj-Xxx** [WongKinYiu/CrossStagePartialNetworks#26]
Due to the limitation of GPU devices, I only tested the model with epoch = 1, and found that compared with the traditional resnext model, the result of cspresnext model for an epoch is not satisfactory. Is it because of the residual link used that the model needs more time to learn

**Comment by WongKinYiu** [comment]
Hello,

I have not checked converge speed of models with and without CSP.
However, all of my experiments follow the same setting as https://pjreddie.com/darknet/imagenet/.
So the training epochs are totally same.

**Comment by zsgj-Xxx** [comment]
Thank you very much for your reply,

I want to do some small tests with CSP
I tried to copy it on the pytorch, but the parameters were worse, I haven't found any problems yet
How to modify the CSP method based on resnext?

**Comment by WongKinYiu** [comment]
the topology of resnet, resnext, and darknet are almost same.
https://github.com/WongKinYiu/CrossStagePartialNetworks/issues/24#issuecomment-623125410 is for your reference.

**Comment by zsgj-Xxx** [comment]
Thank you for your work,

Do I just need to replace Darknet? Layer with resne (x) t? Layer to get the results I need:heart_eyes:

**Comment by zsgj-Xxx** [comment]
Thank you for your work,

I just need to replace darknet_layer with resne(x)t_layer to get the result I need?:heart_eyes:

**Comment by zsgj-Xxx** [comment]
![image](https://user-images.githubusercontent.com/55118073/82009485-00c4fe80-96a2-11ea-8ef1-d4934e966074.png)

In addition, in this figure, after maxpooling, is ① CSP? But I think the parameter displayed is not split, but copy

**Comment by WongKinYiu** [comment]
yes.

i think there will be a convolutional layer behind ①. more details: https://github.com/WongKinYiu/CrossStagePartialNetworks/issues/18

**Comment by zsgj-Xxx** [comment]
![image](https://user-images.githubusercontent.com/55118073/82195894-8a3b3180-992b-11ea-8cfe-378e718a62a9.png)
I'm sorry that I've read the paper and the cfg file over and over again, but I still don't understand it

14 * 14 * 1024 - > whether two 7 * 7 * 1024  branches have also been trained

It looks like
![image](https://user-images.githubusercontent.com/55118073/82196898-dd61b400-992c-11ea-887f-787ac8662dff.png)

**Comment by WongKinYiu** [comment]
14x14 is belong to partial transition layer in previous stage.
