### ISSUE TITLE
Training never starts?

### ISSUE THREAD

**Issue by praneet195** [WongKinYiu/CrossStagePartialNetworks#33]
I used the csresnext50-panet-spp-original-optimal.cfg and the weight file associated with it. I followed the steps mentioned by @AlexeyAB's yolo repo and changed my cfg accordingly. 
I changed all convolution filters before yolo to 18 as I have 1 class and reduced the max_batches to 10000. I also set the steps to 8000,9000.
But I can never start the training. It loads the model and just stops.
How do I fix this?

**Comment by WongKinYiu** [comment]
please add `-clear` at the end of your training command.

**Comment by praneet195** [comment]
Perfect, Thank you for the quick reply :)
