### ISSUE TITLE
The figure about  yolov4 and yolov5

### ISSUE THREAD

**Issue by jzchenriver** [WongKinYiu/CrossStagePartialNetworks#36]
Hello, I find this figure in the issue, which compares the detection results between different yolo.
![84472297-8b0c7c80-acb9-11ea-91a9-49987d70bcfb](https://user-images.githubusercontent.com/45973335/84974490-fccf4500-b155-11ea-91c6-f8e758c60cd1.png)
In the results of each yolov, there are several points. I wanna know the meanings of them. 
Why does AP increase with average latency increases?

**Comment by WongKinYiu** [comment]
each point means different input resolution, for example 288, 352, 416, ...
and this comparison is out-of-date, it is recommend to find the newest comparison in AlexeyAB's or Ultralytics's repository.

**Comment by jzchenriver** [comment]
Thank you for your reply.
In the paper, you evaluate some detection methods on the mobile GPU (Jetson TX2), and mention that CSPPeleeNet Ref.-EFM (SAM) reaches 41 fps on Jetson TX2. 
Are these methods included in this repository? Or where I can find it?

**Comment by WongKinYiu** [comment]
CSPPeleeNet Ref.-EFM (SAM) is a private model.
We will release tiny YOLOv4 soon.

**Comment by jzchenriver** [comment]
I am looking forward to it.

**Comment by yilawu** [comment]
> CSPPeleeNet Ref.-EFM (SAM) is a private model.
> We will release tiny YOLOv4 soon.

hey, can u release the yolov4-tiny with CSP train code?
Thank you.
