### ISSUE TITLE
关于cspdarknet53在imagenet上的分类的训练结果

### ISSUE THREAD

**Issue by njustczr** [WongKinYiu/CrossStagePartialNetworks#40]
你好：
       我看了你的csdarknet53.cfg，里面有如下配置：
angle=7
hue=.1
saturation=.75
exposure=.75
aspect=.75
所以这些增强在imagenet数据集上训练时也加进去了，才得到top1 acc：77%的结果吗？

**Comment by WongKinYiu** [comment]
yes.

**Comment by njustczr** [comment]
> yes.

thanks
