### ISSUE TITLE
Anybody know about the **P6 model** means?

### ISSUE THREAD

**Issue by linhezheng19** [WongKinYiu/CrossStagePartialNetworks#41]
Excuse me，I noticed that in [issue #32 ](https://github.com/WongKinYiu/CrossStagePartialNetworks/issues/32), AlexeyAB and you talked about **P6 model**, what model does it represent? I don't see it in both **CSPNet** and **YOLOv4** paper.

**Comment by WongKinYiu** [comment]
![image](https://user-images.githubusercontent.com/12152972/95058501-35595580-072a-11eb-8b96-207409d00368.png)

original yolov3/v4 make predictions in p3-p5 scales, p6 model means make predictions in p3-p6 scales.

**Comment by linhezheng19** [comment]
I thought it was a new detection structure in CSPNet, so I was little confused. Thank you for your reply.

**Comment by WongKinYiu** [comment]
[structure definition](https://github.com/WongKinYiu/PyTorch_YOLOv4/blob/u5/models/csp-p6-mish.yaml)

**Comment by linhezheng19** [comment]
thank you, i will learn it carefully.
