### ISSUE TITLE
关于cspdarknet53，cfg中weight_decay的设置

### ISSUE THREAD

**Issue by njustczr** [WongKinYiu/CrossStagePartialNetworks#42]
你好，我看你的配置文件cfg/csdarknet53.cfg里面decay=0.0005，但是你的cspnet论文里面写的weight_decay=0.005，包括yolov4论文里面也是写的weight_decay=0.005，实际训练cspdarknet53分类这个差别大吗？

**Comment by WongKinYiu** [comment]
paper裡imagenet的設置寫錯了
training steps多寫了個0: 8000000 => 800000
decay少寫了個0: 0.005 => 0.0005
以code為準

**Comment by njustczr** [comment]
> paper裡imagenet的設置寫錯了
> training steps多寫了個0: 8000000 => 800000
> decay少寫了個0: 0.005 => 0.0005
> 以code為準

好的，谢谢!
